version: "3.8"

name: express

services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express
    image: express
    networks:
      default: null
    ports:
      - mode: ingress
        target: 3000
        published: "3000"
        protocol: tcp
    tty: true

networks:
  default:
    name: express
